services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fastapi-api

    ports:
      - "8000:8000"

    volumes:
      - ./app:/app/app
      - ./startup.sh:/app/startup.sh

    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

    env_file:
      - .env

    command: bash /app/startup.sh